{% set name = "onnxconverter-common" %}
{% set version = "1.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 21588945e9b844826e8326e17ed646f3dd2c2c387fe722b5138559c2567146bf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - packaging
    - python >={{ python_min }}
    - numpy
    - protobuf >=3.20.2
    - onnx

test:
  imports:
    - onnxconverter_common
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/microsoft/onnxconverter-common
  summary: Common utilities for ONNX converters
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
